services:
  # VS Code extension development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${PROJECT_NAME:-vscode-code-share-link}-dev
    volumes:
      - .:/workspace
      # Node.js dependencies
      - /workspace/node_modules
      # VS Code extension test resources
      - /workspace/.vscode-test
      # VS Code related files
      - ${HOME:-/root}/.vscode-server:/root/.vscode-server
    environment:
      - NODE_ENV=development
      - PROJECT_NAME=${PROJECT_NAME:-vscode-code-share-link}
      - DISPLAY=:10
    working_dir: /workspace
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"   # VS Code extension debugging port
    command: /bin/bash